// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NumberCruncher is an autogenerated mock type for the NumberCruncher type
type NumberCruncher struct {
	mock.Mock
}

// Add provides a mock function with given fields: x, y
func (_m *NumberCruncher) Add(x int, y int) int {
	ret := _m.Called(x, y)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(x, y)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Verify provides a mock function with given fields: got, want
func (_m *NumberCruncher) Verify(got int, want int) bool {
	ret := _m.Called(got, want)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(got, want)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
